---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wazuh-indexer-external-secret
  namespace: wazuh
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: wazuh-secret-store
    kind: ClusterSecretStore
  target:
    name: ext-wazuh-indexer-secrets
  data:
    - secretKey: "INDEXER_USERNAME"
      remoteRef:
        key: dev/github/wazuh/indexer
        property: indexer-username
    - secretKey: "INDEXER_PASSWORD"
      remoteRef:
        key: dev/github/wazuh/indexer
        property: indexer-password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wazuh-dashboard-external-secret
  namespace: wazuh
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: wazuh-secret-store
    kind: ClusterSecretStore
  target:
    name: ext-wazuh-dashboard-secrets
  data:
    - secretKey: "DASHBOARD_USERNAME"
      remoteRef:
        key: dev/github/wazuh/indexer
        property: dashboard-username
    - secretKey: "DASHBOARD_PASSWORD"
      remoteRef:
        key: dev/github/wazuh/indexer
        property: dashboard-password
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wazuh-api-external-secret
  namespace: wazuh
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: wazuh-secret-store
    kind: ClusterSecretStore
  target:
    name: ext-wazuh-api-credentials
  data:
    - secretKey: "API_USERNAME"
      remoteRef:
        key: dev/github/wazuh
        property: api-username
    - secretKey: "API_PASSWORD"
      remoteRef:
        key: dev/github/wazuh
        property: api-password