---
# WARNING: This is a development-only secret with a hardcoded token.
# For production environments, use a more secure method to manage Vault tokens.
apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  namespace: external-secrets
type: Opaque
data:
  token: cm9vdC10b2tlbg==  # base64 encoded "root-token"