---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: wazuh-root-ca-external-secret
  namespace: wazuh
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: wazuh-secret-store
    kind: ClusterSecretStore
  target:
    name: ext-wazuh-root-ca-secrets
  data:
    - secretKey: "root-ca.pem"
      remoteRef:
        key: dev/github/wazuh/root
        property: root-ca.pem
    - secretKey: "root-ca-key.pem"
      remoteRef:
        key: dev/github/wazuh/root
        property: root-ca-key.pem