eksa_vms:
  hosts:
    vm1:
      ansible_host: 192.168.1.100 # Replace with your VM's IP address
      ansible_user: ubuntu
      ansible_ssh_private_key_file: ~/.ssh/id_rsa # Replace with your private key path